spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/order_sys?characterEncoding=utf8&autoReConnect=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
server:
  port: 9000
  servlet:
    context-path: /order

